"""встречи строго один на один

Revision ID: 094d950cdb59
Revises: 4e817921e176
Create Date: 2026-10-06 16:39:38.892744
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '094d950cdb59'
down_revision: str | None = '4e817921e176'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_booking_guest_slot'), table_name='bookings', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'confirmed'::character varying])::text[]))")
    op.create_index('uq_booking_active_session', 'bookings', ['session_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.drop_column('event_types', 'max_guests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('max_guests', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('uq_booking_active_session', table_name='bookings', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.create_index(op.f('uq_booking_guest_slot'), 'bookings', ['event_type_id', 'session_id', 'guest_email_bidx'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'confirmed'::character varying])::text[]))")
    # ### end Alembic commands ###
