"""уникальный слаг вида встречи у владельца

Revision ID: 4e817921e176
Revises: d07e7cab84f6
Create Date: 2026-10-06 15:28:50.432806
"""

from collections.abc import Sequence

from alembic import op

revision: str = '4e817921e176'
down_revision: str | None = 'd07e7cab84f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_event_type_owner_slug', 'event_types', ['owner_id', 'slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_event_type_owner_slug', table_name='event_types')
    # ### end Alembic commands ###
