"""встреча в телемосте и очередь писем

Revision ID: 886d9789000d
Revises: 094d950cdb59
Create Date: 2026-10-06 17:24:15.903426
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import backend.crypto

# Импорт `backend.crypto` обязателен: без него `EncryptedText` в этой
# миграции превратится в необъявленное имя и прогон упадёт.
# Автогенерация такой импорт не добавляет, поэтому он дописан руками.


revision: str = '886d9789000d'
down_revision: str | None = '094d950cdb59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('to_email', backend.crypto.EncryptedText(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_kind'), 'outbox_events', ['kind'], unique=False)
    op.add_column('sessions', sa.Column('conference_id', sa.String(length=128), nullable=True))
    op.add_column('sessions', sa.Column('join_url', sa.String(length=512), nullable=True))
    op.add_column('sessions', sa.Column('meeting_password', backend.crypto.EncryptedText(), nullable=True))
    # Значение по умолчанию обязательно: сеансы в таблице уже есть, а
    # колонка не пустая. Без значения по умолчанию миграция упадёт на
    # первой же существующей строке.
    op.add_column('sessions', sa.Column('conference_status', sa.String(length=16), nullable=False, server_default='not_created'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'conference_status')
    op.drop_column('sessions', 'meeting_password')
    op.drop_column('sessions', 'join_url')
    op.drop_column('sessions', 'conference_id')
    op.drop_index(op.f('ix_outbox_events_kind'), table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
