"""расписание, виды встреч, сеансы, заявки

Revision ID: d07e7cab84f6
Revises: cd728cae26bd
Create Date: 2026-10-06 15:01:12.906062
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import backend.crypto

# Импорт `backend.crypto` обязателен: без него `EncryptedText` в этой
# миграции превратится в необъявленное имя и прогон упадёт.
# Автогенерация такой импорт не добавляет, поэтому он дописан руками.


revision: str = 'd07e7cab84f6'
down_revision: str | None = 'cd728cae26bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('weekdays', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_owner_id'), 'schedules', ['owner_id'], unique=False)
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('time_increment_minutes', sa.Integer(), nullable=False),
    sa.Column('min_notice_hours', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_types_owner_id'), 'event_types', ['owner_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_event_type_id'), 'sessions', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_index('uq_session_event_start', 'sessions', ['event_type_id', 'start_at'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', backend.crypto.EncryptedText(), nullable=False),
    sa.Column('guest_email', backend.crypto.EncryptedText(), nullable=False),
    sa.Column('guest_email_bidx', sa.LargeBinary(), nullable=False),
    sa.Column('guest_timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_event_type_id'), 'bookings', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_bookings_owner_id'), 'bookings', ['owner_id'], unique=False)
    op.create_index('ix_bookings_owner_session', 'bookings', ['owner_id', 'session_id'], unique=False)
    op.create_index(op.f('ix_bookings_session_id'), 'bookings', ['session_id'], unique=False)
    op.create_index('uq_booking_guest_slot', 'bookings', ['event_type_id', 'session_id', 'guest_email_bidx'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    # Значение по умолчанию обязательно: колонка не пустая, а эксперты,
    # заведённые до этого этапа, уже лежат в таблице. Без значения по
    # умолчанию миграция упадёт на первой же существующей строке.
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=False, server_default='UTC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_index('uq_booking_guest_slot', table_name='bookings', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.drop_index(op.f('ix_bookings_session_id'), table_name='bookings')
    op.drop_index('ix_bookings_owner_session', table_name='bookings')
    op.drop_index(op.f('ix_bookings_owner_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_event_type_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('uq_session_event_start', table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_event_type_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_event_types_owner_id'), table_name='event_types')
    op.drop_table('event_types')
    op.drop_index(op.f('ix_schedules_owner_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
